apiVersion: v1
generated: "2019-10-13T20:59:12.11806-05:00"
repositories:
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-upxos37ym7
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-nea1kzf6fw
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-jdi9af6xcg
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-463buimijb
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-mmun6kxq4m
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-1au6ug1kmi
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-frdhs41u3o
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-cukfr8mzh7
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-11uaz29497
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-1hwzjtgoqv
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-1guu3fn8kv
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-am0xzz4pwm
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-980p1nae7d
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-3g6xnz9wtb
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-t6r6fl43ex
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-2xutoe3fbm
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-eoon8uz79j
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-ysj31zo9fl
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-cf9ot0roy4
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-3ntybkinj4
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-7qwy83rljc
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-ifuewuytom
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-82fhjivbzl
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-21i87p166d
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-k1h3l167eh
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-v6aez7qjhg
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
- caFile: ""
  certFile: ""
  keyFile: ""
  name: test-repository-sgq6qb8g92
  password: ""
  url: https://kubernetes-charts-incubator.storage.googleapis.com
  username: ""
